//'HelloWorld' PROJECT RETURNS "Hello World!"
//THIS IS A BEGINNER JAVASCRIPT PROGRAM I AM MAKING TO REINFORCE MY LEARNING
//SO DON'T EXPECT OPTIMIZED CODE
//CREATED BY: CHRISTIAN SEIPLE 


//RETURN STRING

console.log("Hello World!");
